import Head from 'next/head'
import MainLayout from "../components/main-layout";
import FilterCity from '../features/filter-city';

function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FilterCity />
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}
export default Home;